/**
 * Command  Description
 * 
 * AT+CMGD  DELETE SMS MESSAGE
 * AT+CMGF  SELECT SMS MESSAGE FORMAT
 * AT+CMGL  LIST SMS MESSAGES FROM PREFERRED STORE
 * AT+CMGR  READ SMS MESSAGE
 * AT+CMGS  SEND SMS MESSAGE
 * AT+CMGW  WRITE SMS MESSAGE TO MEMORY
 * AT+CMSS  SEND SMS MESSAGE FROM STORAGE
 * AT+CNMI  NEW SMS MESSAGE INDICATIONS
 * AT+CPMS  PREFERRED SMS MESSAGE STORAGE
 * AT+CRES  RESTORE SMS SETTINGS
 * AT+CSAS  SAVE SMS SETTINGS
 * AT+CSCA  SMS SERVICE CENTER ADDRESS
 * AT+CSCB  SELECT CELL BROADCAST SMS MESSAGES
 * AT+CSDH  SHOW SMS TEXT MODE PARAMETERS
 * AT+CSMP  SET SMS TEXT MODE PARAMETERS
 * AT+CSMS  SELECT MESSAGE SERVICE
 */
